"""Generate docs/OSM_ROUTES.md from data/osm/vile_parle_summary.json (never hand-edited)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def row(name: str, d: dict, unit: str = "") -> str:
    return f"| {name} | {d['mean']:.2f} | {d['median']:.2f} | {d['p10']:.2f} | {d['p90']:.2f} | {unit} |"


def main() -> None:
    s = json.loads((ROOT / "data" / "osm" / "vile_parle_summary.json").read_text(encoding="utf-8"))
    m, pk = s["routes"]["metrics"], s["routes"]["per_km"]
    w, dr, a = s["walk_network"], s["drive_network"], s["area"]
    lines = [
        "# Real route geometry from OpenStreetMap",
        "",
        f"Generated by `scripts/make_osm_doc.py` from `data/osm/vile_parle_summary.json` (produced by "
        f"`experiments/08_osm_routes.py`). {s['attribution']}. Licence: {s['licence']}.",
        "",
        f"* **Area**: a {a['radius_m'] / 1000:.0f} km disc around \"{a['query']}\" "
        f"({a['centre_lat']:.5f}, {a['centre_lon']:.5f}), Vile Parle West, Mumbai. Retrieved {s['osm_retrieved']['walk']} "
        f"(walk) and {s['osm_retrieved']['drive']} (drive) with OSMnx {s['software']['osmnx']}.",
        f"* **Walking network**: {w['n_nodes']:,} nodes, {w['n_edges_undirected']:,} undirected edges, {w['total_length_km']:.0f} km. "
        f"**Driving network**: {dr['n_nodes']:,} nodes, {dr['n_edges_directed']:,} directed edges.",
        f"* **Sampling**: {s['sampling']['n_pairs']} origin-destination pairs (seed {s['sampling']['seed']}), straight-line distance "
        f"uniform in {s['sampling']['straight_min_m']:.0f}-{s['sampling']['straight_max_m']:.0f} m, both ends snapped to the "
        f"nearest node (at most {s['sampling']['max_snap_m']:.0f} m).",
        "",
        "## Route statistics",
        "",
        "| metric | mean | median | p10 | p90 | unit |",
        "| --- | --- | --- | --- | --- | --- |",
        row("straight-line distance", m["straight_m"], "m"),
        row("walking route length", m["walk_m"], "m"),
        row("walking route factor (walk / straight)", m["walk_factor"]),
        row("driving route length", m["drive_m"], "m"),
        row("driving route factor (drive / straight)", m["drive_factor"]),
        "",
        "The **walking route factor** (median "
        f"{m['walk_factor']['median']:.2f}) is what the rover model uses to turn a straight-line response radius into a route length.",
        "",
        "## What OpenStreetMap does not tell us here (coverage caveat)",
        "",
        f"* Only {w['road_with_sidewalk_tag_share']:.1%} of road length carries a sidewalk tag and {w['road_untagged_for_sidewalk_share']:.1%} "
        f"is untagged for sidewalks; dedicated pedestrian ways are {w['pedestrian_way_length_share']:.1%} of the walking network.",
        f"* The area contains only {w['n_crossing_nodes']} tagged crossing nodes and {w['n_kerb_tagged_nodes']} kerb-tagged node "
        f"({s['routes']['share_pairs_zero_crossings_tagged']:.0%} of sampled routes contain zero tagged crossings).",
        f"* Tagged crossings per km of walking route: pooled {pk['crossings_tagged']['pooled']:.2f}. A geometric fallback that counts "
        f"transversal crossings of primary, secondary and tertiary roads gives pooled {pk['crossings_major']['pooled']:.2f} per km. "
        "Both are **lower bounds**: real streets in this area have far more crossings than the map records.",
        "",
        "## How this feeds the model",
        "",
        "* The walking route factor is used as measured.",
        "* Crossing density is **not** taken from the map. The clinical analysis sweeps crossings per km over the OSM-tagged "
        "lower bound and assumed urban values (2, 4 and 8 per km) and reports every one.",
        "* The driving route factor is reported for context only: the ambulance response-time distribution comes from a published "
        "study (Naess et al. 2024), not from this network.",
        "",
    ]
    (ROOT / "docs" / "OSM_ROUTES.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote docs/OSM_ROUTES.md")


if __name__ == "__main__":
    main()
