"""Generate docs/VALIDATION.md from results/validation_<design>.json (never hand-edited)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def section(design: str) -> list[str]:
    path = ROOT / "results" / f"validation_{design}.json"
    d = json.loads(path.read_text(encoding="utf-8"))
    v, st, ty = d["vehicle"], d["static"], d["tyre"]
    lines = [
        f"## {design.capitalize()} design",
        "",
        f"Wheel radius {v['wheel_radius']:.3f} m, suspension {v['susp_k']:.0f} N/m and {v['susp_c']:.0f} N s/m, "
        f"isolator {v['iso_kz']:.0f} N/m and {v['iso_cz']:.0f} N s/m, motors {v['motor_peak_torque']:.1f} N m.",
        "",
        f"* **Static equilibrium**: ride height {st['ride_height_m'] * 1000:.2f} mm against the designed "
        f"{st['ride_height_expected_m'] * 1000:.2f} mm (error {st['ride_height_err_mm']:+.2f} mm); payload "
        f"accelerometer at rest {st['payload_acc_z']:.3f} m/s^2 (1 g = 9.810).",
        f"* **Effective tyre stiffness** (static penetration under the measured wheel load): "
        f"{ty['kt_eff_N_per_m'] / 1000:.0f} kN/m.",
        "",
        "Free bounce against the eigenvalues of the analytic two-degree-of-freedom quarter-car "
        "(using that tyre stiffness):",
        "",
        "| target damping ratio | measured omega_n [rad/s] | analytic | error | measured zeta | analytic | error |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in d["ringdown"]:
        if "measured_zeta" in r:
            lines.append(f"| {r['zeta_target']:.2f} | {r['measured_omega_n']:.2f} | {r['analytic_omega_n']:.2f} | "
                         f"{r['omega_n_err_pct']:+.1f}% | {r['measured_zeta']:.3f} | {r['analytic_zeta']:.3f} | "
                         f"{r['zeta_err_pct']:+.1f}% |")
    lines += ["", "Straight-line rolling on flat ground:", "",
              "| commanded [m/s] | measured [m/s] | speed error | lateral drift after 10 s |", "| --- | --- | --- | --- |"]
    for r in d["rolling"]:
        lines.append(f"| {r['v_cmd']:.1f} | {r['v_measured']:.3f} | {r['speed_err_pct']:+.2f}% | "
                     f"{r['lateral_drift_m'] * 1000:.1f} mm |")
    sk = d["soak"]
    lines += ["", f"* **Stability soak**: {sk['steps']:,} physics steps of random speed and steering commands over a "
                  f"kerb field, {sk['resets']} resets after leaving the arena, all states finite, peak speed "
                  f"{sk['max_speed_mps']:.2f} m/s.", ""]
    return lines


def main() -> None:
    lines = [
        "# Physics validation",
        "",
        "Generated by `scripts/make_validation_doc.py` from `results/validation_*.json` (produced by "
        "`experiments/01_validate_suspension.py`). Regression tests for the same checks live in "
        "`tests/test_physics.py`.",
        "",
        "The simulator is compared with closed-form mechanics before it is used for anything else. "
        "The steady-state speed droop of about 0.7 percent is the expected offset of a proportional "
        "wheel-speed loop against bearing damping.",
        "",
    ]
    for design in ("nominal", "optimized"):
        lines += section(design)
    (ROOT / "docs" / "VALIDATION.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote docs/VALIDATION.md")


if __name__ == "__main__":
    main()
