"""Verify every DOI in docs/references.json against Crossref.

For each reference the script resolves the DOI, compares the registered title with
the title we cite (normalised, token-overlap), and prints a table. Exit status is
non-zero if any DOI fails to resolve or the titles disagree, so CI can gate on it.

Usage:
    python scripts/verify_citations.py            # check all refs
    python scripts/verify_citations.py --write    # also rewrite docs/REFERENCES.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REF_JSON = ROOT / "docs" / "references.json"
REF_MD = ROOT / "docs" / "REFERENCES.md"
API = "https://api.crossref.org/works/"
UA = "aedrover-citation-check/0.1 (mailto:ishaanmondal2005@gmail.com)"


def _norm(text: str) -> set[str]:
    return set(re.findall(r"[a-z0-9]+", text.lower()))


DATACITE = "https://api.datacite.org/dois/"


def _get_json(url: str) -> dict | None:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return None
        raise


def fetch(doi: str) -> dict | None:
    """Resolve a DOI on Crossref, falling back to DataCite (arXiv DOIs live there)."""
    body = _get_json(API + urllib.parse.quote(doi, safe="/()"))
    if body is not None:
        return body["message"]
    body = _get_json(DATACITE + urllib.parse.quote(doi.lower(), safe="/()"))
    if body is None:
        return None
    attrs = body["data"]["attributes"]
    return {
        "title": [t["title"] for t in attrs.get("titles", [])[:1]],
        "issued": {"date-parts": [[attrs.get("publicationYear")]]},
    }


def title_overlap(cited: str, registered: str) -> float:
    a, b = _norm(cited), _norm(registered)
    return len(a & b) / max(1, min(len(a), len(b)))


def check(refs: list[dict]) -> list[dict]:
    rows = []
    for ref in refs:
        msg = fetch(ref["doi"])
        if msg is None:
            rows.append({**ref, "status": "NOT_FOUND", "registered_title": "", "overlap": 0.0})
            continue
        registered = (msg.get("title") or [""])[0]
        overlap = title_overlap(ref["title"], registered)
        year = None
        for key in ("published-print", "published-online", "issued"):
            parts = (msg.get(key) or {}).get("date-parts")
            if parts and parts[0] and parts[0][0]:
                year = parts[0][0]
                break
        status = "OK" if overlap >= 0.8 else "TITLE_MISMATCH"
        if year is not None and ref.get("year") and int(ref["year"]) != int(year):
            status = "YEAR_MISMATCH"
        rows.append(
            {
                **ref,
                "status": status,
                "registered_title": registered,
                "registered_year": year,
                "overlap": round(overlap, 2),
            }
        )
    return rows


def render_markdown(rows: list[dict]) -> str:
    lines = [
        "# Verified references",
        "",
        "Generated by `scripts/verify_citations.py`. Every entry below resolved on Crossref and its",
        "registered title matched the cited title. Nothing is cited from memory.",
        "",
        "| Key | Citation | DOI | Used for | Crossref |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        cite = f"{r['authors']} ({r['year']}). {r['registered_title'] or r['title']}. *{r['venue']}*"
        lines.append(
            f"| `{r['key']}` | {cite} | [{r['doi']}](https://doi.org/{r['doi']}) "
            f"| {r['role']} | {r['status']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="rewrite docs/REFERENCES.md")
    args = ap.parse_args()

    refs = json.loads(REF_JSON.read_text(encoding="utf-8"))["references"]
    rows = check(refs)
    width = max(len(r["key"]) for r in rows)
    bad = 0
    for r in rows:
        flag = "ok " if r["status"] == "OK" else "BAD"
        bad += r["status"] != "OK"
        print(f"[{flag}] {r['key']:<{width}}  {r['status']:<14} overlap={r['overlap']:.2f}  {r['doi']}")
    if args.write:
        REF_MD.write_text(render_markdown(rows), encoding="utf-8")
        print(f"wrote {REF_MD.relative_to(ROOT)}")
    print(f"{len(rows) - bad}/{len(rows)} references verified")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
