"""Keep the PPO findings up to date automatically.

Parses a training log into a learning curve (CSV + PNG), and once training has finished (the run
directory contains ``meta.json``) runs a held-out evaluation against the classical planner and
regenerates ``docs/PPO_TRAINING.md``. Safe to run at any time and repeatedly; with ``--follow`` it
polls until training completes.

    python scripts/watch_ppo.py --run ppo_shielded              # update whatever exists now
    python scripts/watch_ppo.py --run ppo_shielded --follow     # poll every 5 min until done
    python scripts/watch_ppo.py --run ppo_shielded --no-eval    # curve and document only
"""

from __future__ import annotations

import argparse
import json
import re
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
LINE = re.compile(r"\[\s*([\d.]+)M steps\s+(\d+) fps\]\s+goal ([\d.]+) collision ([\d.]+) stall ([\d.]+)")


def parse_log(path: Path) -> pd.DataFrame:
    rows = [(float(m[1]) * 1e6, int(m[2]), float(m[3]), float(m[4]), float(m[5]))
            for m in map(LINE.search, path.read_text(encoding="utf-8", errors="replace").splitlines()) if m]
    return pd.DataFrame(rows, columns=["steps", "fps", "goal", "collision", "stall"])


def plot_curve(curve: pd.DataFrame, out: Path, title: str) -> None:
    fig, ax = plt.subplots(figsize=(7.5, 3.6))
    s = curve.steps / 1e6
    k = min(5, max(1, len(curve) // 4))
    for col, colour, label in (("goal", "#1b7f5c", "reached goal"), ("collision", "#c0392b", "collision"),
                               ("stall", "#d98c1f", "stalled")):
        ax.plot(s, curve[col], color=colour, alpha=0.25, lw=1)
        ax.plot(s, curve[col].rolling(k, min_periods=1).mean(), color=colour, lw=2, label=label)
    ax.set_xlabel("environment decisions [millions] (10 Hz)")
    ax.set_ylabel("fraction of recent training episodes")
    ax.set_ylim(0, 1.02)
    ax.set_title(title, fontsize=10)
    ax.grid(alpha=0.25)
    ax.legend(loc="center right", frameon=False)
    fig.tight_layout()
    fig.savefig(out, dpi=150)
    plt.close(fig)


def evaluate(run_dir: Path, n: int, workers: int | None) -> pd.DataFrame:
    from aedrover.learning.evaluate import evaluate_policy

    return evaluate_policy(str(run_dir), n=n, workers=workers)


def write_doc(run: str, curve: pd.DataFrame, meta: dict | None, ev: pd.DataFrame | None, out: Path) -> None:
    lines = [
        "# PPO training and findings",
        "",
        f"Generated by `scripts/watch_ppo.py` from the run `{run}`. Do not edit by hand: re-run the script.",
        "",
        "## Training",
        "",
    ]
    if meta:
        lines += [
            f"* {meta['steps'] / 1e6:.2f} M environment decisions (10 Hz), {meta['n_envs']} parallel environments, "
            f"{meta['wall_s'] / 60:.0f} minutes on CPU (PyTorch {meta['torch']}), seed {meta['seed']}.",
            f"* Safety filter in the training loop: {meta['shield']}.",
        ]
    else:
        lines += ["* Training has not finished yet; the curve below is partial."]
    lines += [
        "* Policy: MLP 2 x 256 (tanh) for actor and critic, PPO with GAE, observation normalisation.",
        "* Domain randomisation every episode: scenario family mixture, kerb height 6-16 cm, tyre friction "
        "0.5-1.2 (0.35-0.6 in the slippery family), payload mass, ramps, obstacles, pedestrian streams.",
        "",
        f"![PPO learning curve](../results/{run}_training_curve.png)",
        "",
    ]
    if len(curve):
        tail = curve.tail(max(3, len(curve) // 10))
        best = curve.loc[curve.goal.idxmax()]
        lines += [
            f"Last-10% window of the training statistics: goal {tail.goal.mean():.2f}, collision "
            f"{tail.collision.mean():.2f}, stall {tail.stall.mean():.2f} "
            f"(best single window: goal {best.goal:.2f} at {best.steps / 1e6:.1f} M steps). "
            "These are on-policy rates under the (stochastic) training policy and the wide training "
            "distribution, so they are pessimistic relative to the deterministic held-out evaluation below.",
            "",
        ]
    if ev is not None and len(ev):
        from aedrover.analysis.report import paired_vs_reference, summarize, to_markdown

        sm = summarize(ev)[["controller", "family", "n", "success", "success_lo", "success_hi", "collision",
                            "stall", "time_med", "shock_med", "over_budget"]]
        lines += ["## Held-out evaluation (deterministic policy, unseen seeds 9000+, co-designed vehicle)", "",
                  to_markdown(sm, "{:.2f}"), ""]
        try:
            pv = paired_vs_reference(ev, "dwa")
            keep = pv[(pv.family == "all") & (pv.controller.str.startswith("ppo"))]
            cols = [c for c in ("controller", "metric", "n_pairs", "mean_ctrl", "mean_ref", "mean_diff", "p_holm")
                    if c in keep.columns]
            lines += ["### Paired comparison with the dynamic-window planner (all families pooled)", "",
                      to_markdown(keep[cols], "{:.3f}"), ""]
        except Exception as exc:  # noqa: BLE001 - reporting must never break the training log update
            lines += [f"(paired comparison unavailable: {exc})", ""]
        lines += ["`ppo_noshield` is the same policy evaluated with the safety filter switched off; "
                  "the gap to `ppo` shows how much it leans on the filter.", "",
                  "### Caveats", "",
                  "* **Unequal speed caps.** The policy may command up to 2.6 m/s while the dynamic-window planner "
                  "cruises at 1.8 m/s, so part of the time difference is a speed-cap effect, not planning quality. "
                  "The main benchmark gives every controller the same cap and reports a speed-cap sweep.",
                  "* 40 episodes per family: the Wilson intervals above are wide; the pooled paired tests use 200 pairs.",
                  "* A single training seed. Seed-to-seed variance of PPO is not yet characterised.", ""]
    else:
        lines += ["## Held-out evaluation", "", "Pending: it runs automatically once training finishes.", ""]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def update(run: str, n_eval: int, do_eval: bool, workers: int | None) -> bool:
    run_dir = ROOT / "checkpoints" / run
    log = ROOT / "runs" / f"{run}.log"
    if not log.exists():
        raise SystemExit(f"no training log at {log}")
    curve = parse_log(log)
    (ROOT / "results").mkdir(exist_ok=True)
    curve.to_csv(ROOT / "results" / f"{run}_training_curve.csv", index=False)
    if len(curve):
        plot_curve(curve, ROOT / "results" / f"{run}_training_curve.png", f"PPO training ({run})")
    meta_path = run_dir / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else None
    ev = None
    ev_path = ROOT / "results" / f"{run}_heldout_eval.csv"
    if meta and do_eval:
        if not ev_path.exists() or ev_path.stat().st_mtime < meta_path.stat().st_mtime:
            ev = evaluate(run_dir, n_eval, workers)
            ev.to_csv(ev_path, index=False)
        else:
            ev = pd.read_csv(ev_path)
    elif ev_path.exists():
        ev = pd.read_csv(ev_path)
    doc = "PPO_TRAINING.md" if run == "ppo_shielded" else f"PPO_TRAINING_{run}.md"
    write_doc(run, curve, meta, ev, ROOT / "docs" / doc)
    print(f"updated: {len(curve)} log points, finished={meta is not None}, evaluated={ev is not None}")
    return meta is not None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="ppo_shielded")
    ap.add_argument("--follow", action="store_true", help="poll until training finishes")
    ap.add_argument("--interval", type=int, default=300, help="seconds between polls with --follow")
    ap.add_argument("--n-eval", type=int, default=40, help="held-out episodes per controller and family")
    ap.add_argument("--no-eval", action="store_true")
    ap.add_argument("--workers", type=int, default=None)
    args = ap.parse_args()
    while True:
        done = update(args.run, args.n_eval, not args.no_eval, args.workers)
        if done or not args.follow:
            break
        time.sleep(args.interval)
    _ = np


if __name__ == "__main__":
    main()
